### CVEN 6833 - Final Project
#### Zachary Carpenter
#### Spring 2025

This R Markdown file runs the main body of code for this final project analysis.

#####*Get Libraries*
```{r Get Libraries}
library(dplyr)
library(lubridate)

```

#####*Source Functions*
```{r Source Functions}
```

#####*Read and Format Flow Data*
```{r Read Flow Data}
flowdata_raw <- as.data.frame(read.csv("NatFlowDataCRB_1906_to_2020.csv", header = TRUE, skip = 3))
flowdata_raw <- flowdata_raw[1:(nrow(flowdata_raw)-5),]   # Remove summary rows

flowdata_clean <- flowdata_raw[, !sapply(flowdata_raw, anyNA)]    # Remove NA columns

flowdata_ub <- flowdata_clean[, 1:21]   # Restrict to just upper basin gages

flowdata_ub$Date <- ymd(flowdata_ub$Date)    # Converts date column to date type object

flowdata_ub_AMJ <- flowdata_ub %>% filter(month(Date) %in% 4:6)   # Filter to just spring flow (A-J)

# Convert flow data to numeric and remove commas from entries
flowdata_ub_AMJ[, 2:ncol(flowdata_ub_AMJ)] <- lapply(
  flowdata_ub_AMJ[, 2:ncol(flowdata_ub_AMJ)], 
  function(col) as.numeric(gsub(",", "", col)))


# Loop structure to sum the annual spring flow for each year and Upper Basin gage location
ann_spring_flow <- matrix(nrow = length(1906:2020), ncol = ncol(flowdata_ub_AMJ)-1) 
yrs <- as.numeric(1906:2020)

for(i in 1:length(yrs)){
  for(j in 2:ncol(flowdata_ub_AMJ)){
    ann_spring_flow[i, j - 1] = sum(flowdata_ub_AMJ[[j]][year(flowdata_ub_AMJ$Date) == yrs[i]], na.rm = TRUE)
  }
}

```